export const data = [
    {
        name: 'Alakazam',
        type: 'Pokemon',
        description: 'Alakazam is pokemon #65, does not know how to use spoons',
        img: 'alakazam.png',
    },
    {
        name: 'Aave',
        type: 'Crypto',
        description: 'Aave is an open source and non-custodial liquidity protocol for earning interest and blabhhblahblah.',
        img: 'aave.png',
    },
    {
        name: 'Charizard',
        type: 'Pokemon',
        description: 'Charizard is a fire-dragon, it does not like water, please do not water the charizard',
        img: 'charizard.png',
    },
    {
        name: 'Doge',
        type: 'Crypto',
        description: 'the one that papa Elon likes',
        img: 'dogecoin.jpeg',
    },
    {
        name: 'Absol',
        type: 'Pokemon',
        description: 'Most badass pokemon out there watch out',
        img: 'absol.png',
    },
    {
        name: 'Arceus',
        type: 'Pokemon',
        description: 'Normal-type Mythical Pokémon introduced in Gen IV. This Pokémon is known as the creator of the Pokémon world.',
        img: 'arceus.png',
    },
    {
        name: 'Bitcoin',
        type: 'Crypto',
        description: 'Bitcoin is a digital currency which operates free of any central control or the oversight of banks or governments.',
        img: 'bitcoin.jpeg',
    },
    {
        name: 'Ethereum',
        type: 'Crypto',
        description: 'Ethereum is a decentralized, open-source blockchain with smart contract functionality.',
        img: 'ethereum.png',
    },
    {
        name: 'Flareon',
        type: 'Pokemon',
        description: 'Fire-type Pokemon introduced in Gen I. Its fire type, so, its awesome',
        img: 'flareon.png',
    },
    {
        name: 'Jirachi',
        type: 'Pokemon',
        description: 'The wishmaker steel/psychic mythical pokemon!',
        img: 'jirachi.jpeg',
    },
    {
        name: 'Lambo',
        type: 'Crypto',
        description: 'when lambo',
        img: 'lambo.jpg',
    },
    {
        name: 'Latios',
        type: 'Pokemon',
        description: 'Psychic dragon type pokemon from Hoenn. Really cool',
        img: 'latios.png',
    },
    {
        name: 'Loopring',
        type: 'Crypto',
        description: 'Loopring is an Ethereum zkRollup protocol: a layer-2 (L2) scaling solution',
        img: 'loopring.png',
    },
    {
        name: 'Metamask',
        type: 'Crypto',
        description: 'A crypto wallet & gateway to blockchain apps',
        img: 'metamask.png',
    },
    {
        name: 'Pikachu',
        type: 'Pokemon',
        description: 'funny yellow dude',
        img: 'pikachu.png',
    },
    {
        name: 'Plug',
        type: 'Crypto',
        description: 'Wallet that lets you access ICP, NFTs, and other tokens as well as log into IC apps',
        img: 'plug.jpeg',
    },
    {
        name: 'Rugpull',
        type: 'Crypto',
        description: 'malicious maneuver where devs abandon a project and run away with all the money',
        img: 'rugpull.png',
    },
    {
        name: 'Terra',
        type: 'Crypto',
        description: 'protocol that uses fiat-pegged stablecoins to power price-stable global payments systems',
        img: 'terra.png',
    },
    {
        name: 'Terrakion',
        type: 'Pokemon',
        description: 'Legendary badass looking Pokemon from gen V',
        img: 'terrakion.png', 
    }
];